# Change these first
owner: meshmonk # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://meshmonk.com
  - name: MeshMonk Bridge
    url: https://bridge.meshmonk.com
  - name: MeshMonk Bridge API
    url: https://api.meshmonk.com/api/v1/ping


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.meshmonk.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://meshmonk.com/assets/img/meshmonk.png
  logoHref: https://meshmonk.com
  favicon: https://formsure.co/assets/favicons/favicon-16x16.png?v=rMBOpxyMqM
  name: "MeshMonk"
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: ""
  
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
